@startuml 02_traceabilities_diagram
allowmixing
skinparam style strictuml

package "Use Cases" {
  usecase "Заказать такси" as uc_purchase
  usecase "Выполнить поездку" as uc_execute
}

package "Use-Case Realizations" {
  class "PurchaseRealization" as r_purchase <<realization>>
  class "ExecuteRealization" as r_execute <<realization>>
}

package "Design Model" {
  class RideController
  class Ride
  class DriverController
  class Driver
}

r_purchase ..> uc_purchase : <<trace>>
r_execute ..> uc_execute : <<trace>>

r_purchase ..> RideController
r_purchase ..> Ride
r_execute ..> DriverController
r_execute ..> Driver
@enduml
